# Klasifikasi menggunakan naive bayes classifier pada python

In [92]:
import math
import random
from collections import defaultdict
from pprint import pprint

#
import warnings
warnings.filterwarnings(action='ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#
sns.set_style(style='white')
sns.set_context(context='notebook', font_scale=1.3, rc={'figure.figsize': (16,9)})

In [93]:
df = pd.read_excel (r'data_training_tugas_akhir.xlsx')
df=pd.DataFrame(df)
df.head()

No        from_user                                              tweet  \
0   1    MarlianaShela  raksasa drone china geram produk perang rusia ...   
1   2      tribunmedan  jenderal rusia buka buka ambisi presiden putin...   
2   3  21BeritaTerkini  perang ukraina konten palsu invasi rusia banji...   
3   4       Beritasatu  as rusia gagal capai tuju perang ukraina cozle...   
4   5   liputan6dotcom  imf ekonomi asia hadap stagflasi imbas perang ...   

    kelas  label  
0  kontra     -1  
1  kontra     -1  
2  kontra     -1  
3  kontra     -1  
4  kontra     -1

In [94]:
df

No        from_user                                              tweet  \
0      1    MarlianaShela  raksasa drone china geram produk perang rusia ...   
1      2      tribunmedan  jenderal rusia buka buka ambisi presiden putin...   
2      3  21BeritaTerkini  perang ukraina konten palsu invasi rusia banji...   
3      4       Beritasatu  as rusia gagal capai tuju perang ukraina cozle...   
4      5   liputan6dotcom  imf ekonomi asia hadap stagflasi imbas perang ...   
..   ...              ...                                                ...   
129  130  muhamma74947158  rusia temu harta karun prajurit ukraina tewas ...   
130  131  iniakunketigaku  noyaliberal are highly appreciated halo guys m...   
131  132     Ngadrunisasi  asumsico semenjak perang rusia vs ukraina udh ...   
132  133    Imor_Idnaiped  agusmenghilang privetbro1 sampe rusia dukung c...   
133  134   sportdoctorapb  juanmahaganti here ekky adyscore s detikcom lh...   

      kelas  label  
0    kontra     -1  
1    kontra     -1  
2    kontra     -1  
3    kontra     -1  
4    kontra     -1  
..      ...    ...  
129     pro      1  
130     pro      1  
131     pro      1  
132     pro      1  
133     pro      1  

[134 rows x 5 columns]

In [95]:
df.label.value_counts()

-1    77
 1    57
Name: label, dtype: int64

In [96]:
df.tweet

0      raksasa drone china geram produk perang rusia ...
1      jenderal rusia buka buka ambisi presiden putin...
2      perang ukraina konten palsu invasi rusia banji...
3      as rusia gagal capai tuju perang ukraina cozle...
4      imf ekonomi asia hadap stagflasi imbas perang ...
                             ...                        
129    rusia temu harta karun prajurit ukraina tewas ...
130    noyaliberal are highly appreciated halo guys m...
131    asumsico semenjak perang rusia vs ukraina udh ...
132    agusmenghilang privetbro1 sampe rusia dukung c...
133    juanmahaganti here ekky adyscore s detikcom lh...
Name: tweet, Length: 134, dtype: object

# transform tweet menjadi features

In [97]:
from sklearn.feature_extraction.text import TfidfVectorizer

s1="makin ga jelas cara kerja bpjs bagaimana negara bisa sejahtera rakyat bila kerja pakai model tambal sulam"
s2="lama amat ngurus bpjs"

vect = TfidfVectorizer()
X = vect.fit_transform([s1, s2])

X.toarray()

array([[0.        , 0.23245605, 0.23245605, 0.23245605, 0.1653944 ,
        0.23245605, 0.23245605, 0.23245605, 0.4649121 , 0.        ,
        0.23245605, 0.23245605, 0.23245605, 0.        , 0.23245605,
        0.23245605, 0.23245605, 0.23245605, 0.23245605],
       [0.53404633, 0.        , 0.        , 0.        , 0.37997836,
        0.        , 0.        , 0.        , 0.        , 0.53404633,
        0.        , 0.        , 0.        , 0.53404633, 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [98]:
list(zip(X.toarray()[0], vect.get_feature_names()))

[(0.0, 'amat'),
 (0.2324560524556355, 'bagaimana'),
 (0.2324560524556355, 'bila'),
 (0.2324560524556355, 'bisa'),
 (0.16539439585841764, 'bpjs'),
 (0.2324560524556355, 'cara'),
 (0.2324560524556355, 'ga'),
 (0.2324560524556355, 'jelas'),
 (0.464912104911271, 'kerja'),
 (0.0, 'lama'),
 (0.2324560524556355, 'makin'),
 (0.2324560524556355, 'model'),
 (0.2324560524556355, 'negara'),
 (0.0, 'ngurus'),
 (0.2324560524556355, 'pakai'),
 (0.2324560524556355, 'rakyat'),
 (0.2324560524556355, 'sejahtera'),
 (0.2324560524556355, 'sulam'),
 (0.2324560524556355, 'tambal')]

In [99]:
list(zip(X.toarray()[1], vect.get_feature_names()))

[(0.534046329052269, 'amat'),
 (0.0, 'bagaimana'),
 (0.0, 'bila'),
 (0.0, 'bisa'),
 (0.37997836159100784, 'bpjs'),
 (0.0, 'cara'),
 (0.0, 'ga'),
 (0.0, 'jelas'),
 (0.0, 'kerja'),
 (0.534046329052269, 'lama'),
 (0.0, 'makin'),
 (0.0, 'model'),
 (0.0, 'negara'),
 (0.534046329052269, 'ngurus'),
 (0.0, 'pakai'),
 (0.0, 'rakyat'),
 (0.0, 'sejahtera'),
 (0.0, 'sulam'),
 (0.0, 'tambal')]

In [100]:
vect= TfidfVectorizer(max_features=1000, binary=True)
X = vect.fit_transform(df.tweet)

X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Membagi data training dan data test untuk menghitung akurasi model

In [101]:
from sklearn.model_selection import train_test_split

x=df.tweet
y=df.label

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [102]:
#from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(max_features=1000, binary=True,)

X_train_vect = vect.fit_transform(X_train)

In [103]:
#!pip install imblearn
#pip intall SMOTE
#from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

sm = SMOTE()

X_train_res, y_train_res = sm.fit_resample(X_train_vect, y_train)

In [104]:
unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))

[(-1, 59), (1, 59)]


# Naive bayes classification

In [105]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train_res, y_train_res)

nb.score(X_train_res, y_train_res)

0.9830508474576272

In [106]:
X_test_vect = vect.transform(X_test)

y_pred = nb.predict(X_test_vect)

y_pred

array([-1, -1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1, -1,  1, -1, -1,  1], dtype=int64)

In [107]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

print("Accuracy : {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score : {:.2f}%".format(f1_score(y_test, y_pred, average='weighted')*100))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred))

Accuracy : 77.78%

F1 Score : 78.41%

Confusion Matrix : 
 [[13  5]
 [ 1  8]]


# proses training naive bayes classification

In [108]:
import os 
import pickle
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

x = df.tweet
y = df.label

text_classifier = Pipeline([('vect', TfidfVectorizer()), ('tfidf', TfidfTransformer()), ('classifier', MultinomialNB(alpha=1.0)),])

X_train = np.asarray(x)
Model_classifier_nbc = text_classifier.fit(X_train, np.asarray(y))

In [109]:
tweet_test = ['pemerintah indonesia harus menentukan pihak mana yang di dukung',
             'mendukung rusia untuk melawan barat dan sekutunya',
             'rusia bikin harga pada naik aja lu perang gw yang repot',
             'ukraina terlalu sombong melawan putin dan rusia',
             'presiden ukraina harusnya mundur saja demi keselematan rakyar',
             'perang ini kan demi membela tanah rusia harus nya dunia engga ikut campur',
             'sebagai orang indonesi gw mendukung rusia buat lawan amerika si',
             'ini perang rusia dan ukraina masalah internal amerika jangan ikut campur deh',
              'kalo jadi ukraina nyerah aja deh sama rusia daripada lama',
             'perang yang cuma bikin harga harga pada naik aja mereka enak udah kaya']

In [110]:
pd.DataFrame(tweet_test)

0
0  pemerintah indonesia harus menentukan pihak ma...
1  mendukung rusia untuk melawan barat dan sekutunya
2  rusia bikin harga pada naik aja lu perang gw y...
3    ukraina terlalu sombong melawan putin dan rusia
4  presiden ukraina harusnya mundur saja demi kes...
5  perang ini kan demi membela tanah rusia harus ...
6  sebagai orang indonesi gw mendukung rusia buat...
7  ini perang rusia dan ukraina masalah internal ...
8  kalo jadi ukraina nyerah aja deh sama rusia da...
9  perang yang cuma bikin harga harga pada naik a...

In [111]:
predicted = Model_classifier_nbc.predict(np.asarray(tweet_test))
predicted

array([ 1,  1, -1,  1, -1,  1,  1,  1,  1, -1], dtype=int64)

In [112]:
result_tweet = []

for i in range(len(predicted)):
    if(predicted[i]==1):
        sentiment_result='PRO'
    elif(predicted[i]==-1):
        sentiment_result='KONTRA'
    result_tweet.append({'tweet':tweet_test[i], 'class':predicted[i], 'result_nbc':sentiment_result})

In [113]:
data=pd.DataFrame(result_tweet)
data

tweet  class result_nbc
0  pemerintah indonesia harus menentukan pihak ma...      1        PRO
1  mendukung rusia untuk melawan barat dan sekutunya      1        PRO
2  rusia bikin harga pada naik aja lu perang gw y...     -1     KONTRA
3    ukraina terlalu sombong melawan putin dan rusia      1        PRO
4  presiden ukraina harusnya mundur saja demi kes...     -1     KONTRA
5  perang ini kan demi membela tanah rusia harus ...      1        PRO
6  sebagai orang indonesi gw mendukung rusia buat...      1        PRO
7  ini perang rusia dan ukraina masalah internal ...      1        PRO
8  kalo jadi ukraina nyerah aja deh sama rusia da...      1        PRO
9  perang yang cuma bikin harga harga pada naik a...     -1     KONTRA