# Klasifikasi menggunakan naive bayes classifier pada python

In [1]:
import math
import random
from collections import defaultdict
from pprint import pprint

#
import warnings
warnings.filterwarnings(action='ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#
sns.set_style(style='white')
sns.set_context(context='notebook', font_scale=1.3, rc={'figure.figsize': (16,9)})

In [2]:
df = pd.read_excel (r'data_training_uas.xlsx')
df=pd.DataFrame(df)
df.head()

Unnamed: 0     from_user  \
0           0       KMielva   
1           1  MuriLesmana1   
2           2     akufelfel   
3           3    AnaSire9ar   
4           4     rajainfo1   

                                                text    kelas  label  
0  nsukahar dennysiregar7 ekokuntadhi divhumas po...  NEGATIF     -1  
1                         minyak goreng urusin bener  NEGATIF     -1  
2  beras jagung bawang merah cabai cabai rawit da...  NEGATIF     -1  
3       pengamatekonom minyak goreng posisi mei kira  NEGATIF     -1  
4  kang bojes sebab harga minyak goreng mahal cox...  NEGATIF     -1

In [3]:
df

Unnamed: 0        from_user  \
0             0          KMielva   
1             1     MuriLesmana1   
2             2        akufelfel   
3             3       AnaSire9ar   
4             4        rajainfo1   
..          ...              ...   
211         189  EkaFitr36468936   
212         190  Jmus_Kalimasada   
213         191   Chansu83052684   
214         192         archdann   
215         193    alydrusbella1   

                                                  text    kelas  label  
0    nsukahar dennysiregar7 ekokuntadhi divhumas po...  NEGATIF     -1  
1                           minyak goreng urusin bener  NEGATIF     -1  
2    beras jagung bawang merah cabai cabai rawit da...  NEGATIF     -1  
3         pengamatekonom minyak goreng posisi mei kira  NEGATIF     -1  
4    kang bojes sebab harga minyak goreng mahal cox...  NEGATIF     -1  
..                                                 ...      ...    ...  
211  warga pidie terima sembako uang minyak goreng ...  POSITIF      1  
212  cair sembako uang minyak goreng kantor pos ayo...  POSITIF      1  
213  sukmajati id rkyt rindu era sby listrik murah ...  POSITIF      1  
214  fenomena jht cair usia pensiun tc 10 juta up b...  POSITIF      1  
215  positivcovid bahagia emak emak vaksin kodim ja...  POSITIF      1  

[216 rows x 5 columns]

In [4]:
df.label.value_counts()

-1    108
 1    108
Name: label, dtype: int64

In [6]:
df.text

0      nsukahar dennysiregar7 ekokuntadhi divhumas po...
1                             minyak goreng urusin bener
2      beras jagung bawang merah cabai cabai rawit da...
3           pengamatekonom minyak goreng posisi mei kira
4      kang bojes sebab harga minyak goreng mahal cox...
                             ...                        
211    warga pidie terima sembako uang minyak goreng ...
212    cair sembako uang minyak goreng kantor pos ayo...
213    sukmajati id rkyt rindu era sby listrik murah ...
214    fenomena jht cair usia pensiun tc 10 juta up b...
215    positivcovid bahagia emak emak vaksin kodim ja...
Name: text, Length: 216, dtype: object

# transform tweet menjadi features

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

s1="makin ga jelas cara kerja bpjs bagaimana negara bisa sejahtera rakyat bila kerja pakai model tambal sulam"
s2="lama amat ngurus bpjs"

vect = TfidfVectorizer()
X = vect.fit_transform([s1, s2])

X.toarray()

array([[0.        , 0.23245605, 0.23245605, 0.23245605, 0.1653944 ,
        0.23245605, 0.23245605, 0.23245605, 0.4649121 , 0.        ,
        0.23245605, 0.23245605, 0.23245605, 0.        , 0.23245605,
        0.23245605, 0.23245605, 0.23245605, 0.23245605],
       [0.53404633, 0.        , 0.        , 0.        , 0.37997836,
        0.        , 0.        , 0.        , 0.        , 0.53404633,
        0.        , 0.        , 0.        , 0.53404633, 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [8]:
list(zip(X.toarray()[0], vect.get_feature_names()))

[(0.0, 'amat'),
 (0.2324560524556355, 'bagaimana'),
 (0.2324560524556355, 'bila'),
 (0.2324560524556355, 'bisa'),
 (0.16539439585841764, 'bpjs'),
 (0.2324560524556355, 'cara'),
 (0.2324560524556355, 'ga'),
 (0.2324560524556355, 'jelas'),
 (0.464912104911271, 'kerja'),
 (0.0, 'lama'),
 (0.2324560524556355, 'makin'),
 (0.2324560524556355, 'model'),
 (0.2324560524556355, 'negara'),
 (0.0, 'ngurus'),
 (0.2324560524556355, 'pakai'),
 (0.2324560524556355, 'rakyat'),
 (0.2324560524556355, 'sejahtera'),
 (0.2324560524556355, 'sulam'),
 (0.2324560524556355, 'tambal')]

In [9]:
list(zip(X.toarray()[1], vect.get_feature_names()))

[(0.534046329052269, 'amat'),
 (0.0, 'bagaimana'),
 (0.0, 'bila'),
 (0.0, 'bisa'),
 (0.37997836159100784, 'bpjs'),
 (0.0, 'cara'),
 (0.0, 'ga'),
 (0.0, 'jelas'),
 (0.0, 'kerja'),
 (0.534046329052269, 'lama'),
 (0.0, 'makin'),
 (0.0, 'model'),
 (0.0, 'negara'),
 (0.534046329052269, 'ngurus'),
 (0.0, 'pakai'),
 (0.0, 'rakyat'),
 (0.0, 'sejahtera'),
 (0.0, 'sulam'),
 (0.0, 'tambal')]

In [11]:
vect= TfidfVectorizer(max_features=1000, binary=True)
X = vect.fit_transform(df.text)

X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.22640839, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Membagi data training dan data test untuk menghitung akurasi model

In [13]:
from sklearn.model_selection import train_test_split

x=df.text
y=df.label

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [14]:
#from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(max_features=1000, binary=True,)

X_train_vect = vect.fit_transform(X_train)

In [15]:
#!pip install imblearn
#pip intall SMOTE
#from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

sm = SMOTE()

X_train_res, y_train_res = sm.fit_resample(X_train_vect, y_train)

In [16]:
unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))

[(-1, 89), (1, 89)]


# Naive bayes classification

In [17]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train_res, y_train_res)

nb.score(X_train_res, y_train_res)

0.9606741573033708

In [18]:
X_test_vect = vect.transform(X_test)

y_pred = nb.predict(X_test_vect)

y_pred

array([ 1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,
        1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1,  1, -1, -1,  1], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

print("Accuracy : {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score : {:.2f}%".format(f1_score(y_test, y_pred, average='weighted')*100))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred))

Accuracy : 81.82%

F1 Score : 81.82%

Confusion Matrix : 
 [[15  4]
 [ 4 21]]


# proses training naive bayes classification

In [22]:
import os 
import pickle
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

x = df.text
y = df.label

text_classifier = Pipeline([('vect', TfidfVectorizer()), ('tfidf', TfidfTransformer()), ('classifier', MultinomialNB(alpha=1.0)),])

X_train = np.asarray(x)
Model_classifier_nbc = text_classifier.fit(X_train, np.asarray(y))

In [64]:
tweet_test = pd.read_csv (r'data_testing_uas.csv')


AttributeError: 'DataFrame' object has no attribute 'type'

In [62]:
tweet_test = ['pemerintah indonesia harus menentukan pihak mana yang di dukung',
             'mendukung rusia untuk melawan barat dan sekutunya',
             'ayo percaya jokowi naik harga sembako bbm minyak goreng']

tweet_test

['pemerintah indonesia harus menentukan pihak mana yang di dukung',
 'mendukung rusia untuk melawan barat dan sekutunya',
 'ayo percaya jokowi naik harga sembako bbm minyak goreng']

In [57]:
pd.DataFrame(tweet_test)

tweet_test
0   'ayo percaya jokowi naik harga sembako bbm min...
1   '86 684 warga pandeglang blt minyak goreng ayo...
2   'cahyaniika3 blt minyak goreng cair minggu kan...
3   'makan bahan minyak goreng alternatif menu seh...
4   'pemkab kubu raya unik distribusi minyak goren...
5   'perintah gelontor rp695 triliun bantu langsun...
6   'ayo percaya jokowi blt minyak goreng cair min...
7   'masreyhaan sorry zaman habibie beras harga 60...
8   'an asosiasi dagang pasar mang penting preside...
9   'sobat bumn bumn holding pangan distribusi min...
10  'pasti dian minyak goreng kapolres jaktim kunj...
11  'bumn holding pangan distribusi minyak goreng ...
12  'mantap berkat kerja keras perintah stok minya...
13  'giat bhabinkamtibmas kel beras basah polsek p...
14  'henryj4ck alingabalinnew alingabalinnew kemen...
15  'salah alas dukung ridwankamil beliau solutif ...
16  'hujan besti untung salur blt minyak goreng ka...
17  'litachanlai2 alhamdulillah berkah puasa minya...
18  'riah acara damai indonesia tvone kemarin sina...
19  'realisasi salur blt minyak goreng surabaya ca...
20  'mandiraja babinsa koramil 07 mandiraja monito...
21  'giat bhabinkamtimas polsek sipispis monitorin...
22  'ridwan kamil lepas kirim perdana minyak goren...
23  'distribusi blt minyak goreng ntb target tunta...
24  'daftar blt minyak goreng rp 300 ribu online c...
25  'perintah laku cepat distribusi blt minyak gor...
26  'lapis masyarakat suka cita blt minyak goreng ...
27  'renahoston178 rakornas program bantu tunai pa...
28  'salur beras usaha abdul rasyid salur 100 ribu...
29  'perintah terbit atur sedia minyak goreng usah...
30  'nay 22ratauwin miring22nya im win22euy boro2 ...
31  'serda rudiyanto koptu jumadi anggota koramil ...
32                     'speedtrap bagi minyak goreng'
33  'giat operasi pasar rangka stabilisasi harga m...
34  'konsultan pr pikir belokin isu terorisme radi...
35  'busetdah78 msaid didu tingkah rakyat rezim ka...
36  'dennysiregar7 utang ugal rezim naik bbm rezim...
37  'e100ss surabaya cepat salur bpnt blt minyak g...
38  'corona hilang muncul naik bbm minyak goreng h...
39  'detik harga migor negeri produsen timbun tung...
40  'salur blt minyak goreng tanggung target rampu...
41  'snowfreesia first goreng minyak and tunggu ai...
42  'kepala dinas sosial provinsi jawa barat sekre...
43  'polres minsel cek sedia minyak goreng pasar t...
44  'sertu surip bripka arifin laksana damping gia...
45  'regional adakan bazar murah minyak goreng kom...
46  'nastar wisman kenal minyak goreng 1 liter par...
47  'serda rudiyanto koptu jumadi anggota koramil ...
48  'perintah awal harga distribusi minyak goreng ...
49  'malu udah uang hutang sana kurang tambah raky...
50  'ngasih parsel budeh2 isi minyak goreng mevvaa...
51  'perintah blt minyak goreng masyarakat dampak ...
52  'perintah awal harga distribusi minyak goreng ...
53  'sunda fess sok farollback uy senderna nugabut...
54  'ridwan kamil cocok lanjut kerja presiden joko...
55  'elzanurjayanti atm cs bri ngantri cs bri kaya...
56  'coeuhh1tpdjm najam polres ppu monitoring stok...
57  'chitaglorya mpok kampung halaman ku ukraina l...
58  'cnnindonesia daftar blt minyak goreng co2nmvk...
59  'krmtroysuryo2 hal2 dasar tsb pajak2 minyak go...

In [58]:
predicted = Model_classifier_nbc.predict(np.asarray(tweet_test))
predicted

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

In [59]:
result_tweet = []

for i in range(len(predicted)):
    if(predicted[i]==1):
        sentiment_result='POSITIF'
    elif(predicted[i]==-1):
        sentiment_result='NEGATIF'
    result_tweet.append({'tweet':tweet_test[i], 'class':predicted[i], 'result_nbc':sentiment_result})

KeyError: 0

In [60]:
data=pd.DataFrame(result_tweet)
data

Empty DataFrame
Columns: []
Index: []