# Klasifikasi menggunakan naive bayes classifier pada python

In [1]:
import math
import random
from collections import defaultdict
from pprint import pprint

#
import warnings
warnings.filterwarnings(action='ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#
sns.set_style(style='white')
sns.set_context(context='notebook', font_scale=1.3, rc={'figure.figsize': (16,9)})

In [2]:
df = pd.read_excel (r'data_training_uas.xlsx')
df=pd.DataFrame(df)
df.head()

Unnamed: 0     from_user  \
0           0       KMielva   
1           1  MuriLesmana1   
2           2     akufelfel   
3           3    AnaSire9ar   
4           4     rajainfo1   

                                                text    kelas  label  
0  nsukahar dennysiregar7 ekokuntadhi divhumas po...  NEGATIF     -1  
1                         minyak goreng urusin bener  NEGATIF     -1  
2  beras jagung bawang merah cabai cabai rawit da...  NEGATIF     -1  
3       pengamatekonom minyak goreng posisi mei kira  NEGATIF     -1  
4  kang bojes sebab harga minyak goreng mahal cox...  NEGATIF     -1

In [3]:
df

Unnamed: 0        from_user  \
0             0          KMielva   
1             1     MuriLesmana1   
2             2        akufelfel   
3             3       AnaSire9ar   
4             4        rajainfo1   
..          ...              ...   
211         189  EkaFitr36468936   
212         190  Jmus_Kalimasada   
213         191   Chansu83052684   
214         192         archdann   
215         193    alydrusbella1   

                                                  text    kelas  label  
0    nsukahar dennysiregar7 ekokuntadhi divhumas po...  NEGATIF     -1  
1                           minyak goreng urusin bener  NEGATIF     -1  
2    beras jagung bawang merah cabai cabai rawit da...  NEGATIF     -1  
3         pengamatekonom minyak goreng posisi mei kira  NEGATIF     -1  
4    kang bojes sebab harga minyak goreng mahal cox...  NEGATIF     -1  
..                                                 ...      ...    ...  
211  warga pidie terima sembako uang minyak goreng ...  POSITIF      1  
212  cair sembako uang minyak goreng kantor pos ayo...  POSITIF      1  
213  sukmajati id rkyt rindu era sby listrik murah ...  POSITIF      1  
214  fenomena jht cair usia pensiun tc 10 juta up b...  POSITIF      1  
215  positivcovid bahagia emak emak vaksin kodim ja...  POSITIF      1  

[216 rows x 5 columns]

In [4]:
df.label.value_counts()

-1    108
 1    108
Name: label, dtype: int64

In [6]:
df.text

0      nsukahar dennysiregar7 ekokuntadhi divhumas po...
1                             minyak goreng urusin bener
2      beras jagung bawang merah cabai cabai rawit da...
3           pengamatekonom minyak goreng posisi mei kira
4      kang bojes sebab harga minyak goreng mahal cox...
                             ...                        
211    warga pidie terima sembako uang minyak goreng ...
212    cair sembako uang minyak goreng kantor pos ayo...
213    sukmajati id rkyt rindu era sby listrik murah ...
214    fenomena jht cair usia pensiun tc 10 juta up b...
215    positivcovid bahagia emak emak vaksin kodim ja...
Name: text, Length: 216, dtype: object

# transform tweet menjadi features

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

s1="makin ga jelas cara kerja bpjs bagaimana negara bisa sejahtera rakyat bila kerja pakai model tambal sulam"
s2="lama amat ngurus bpjs"

vect = TfidfVectorizer()
X = vect.fit_transform([s1, s2])

X.toarray()

array([[0.        , 0.23245605, 0.23245605, 0.23245605, 0.1653944 ,
        0.23245605, 0.23245605, 0.23245605, 0.4649121 , 0.        ,
        0.23245605, 0.23245605, 0.23245605, 0.        , 0.23245605,
        0.23245605, 0.23245605, 0.23245605, 0.23245605],
       [0.53404633, 0.        , 0.        , 0.        , 0.37997836,
        0.        , 0.        , 0.        , 0.        , 0.53404633,
        0.        , 0.        , 0.        , 0.53404633, 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [8]:
list(zip(X.toarray()[0], vect.get_feature_names()))

[(0.0, 'amat'),
 (0.2324560524556355, 'bagaimana'),
 (0.2324560524556355, 'bila'),
 (0.2324560524556355, 'bisa'),
 (0.16539439585841764, 'bpjs'),
 (0.2324560524556355, 'cara'),
 (0.2324560524556355, 'ga'),
 (0.2324560524556355, 'jelas'),
 (0.464912104911271, 'kerja'),
 (0.0, 'lama'),
 (0.2324560524556355, 'makin'),
 (0.2324560524556355, 'model'),
 (0.2324560524556355, 'negara'),
 (0.0, 'ngurus'),
 (0.2324560524556355, 'pakai'),
 (0.2324560524556355, 'rakyat'),
 (0.2324560524556355, 'sejahtera'),
 (0.2324560524556355, 'sulam'),
 (0.2324560524556355, 'tambal')]

In [9]:
list(zip(X.toarray()[1], vect.get_feature_names()))

[(0.534046329052269, 'amat'),
 (0.0, 'bagaimana'),
 (0.0, 'bila'),
 (0.0, 'bisa'),
 (0.37997836159100784, 'bpjs'),
 (0.0, 'cara'),
 (0.0, 'ga'),
 (0.0, 'jelas'),
 (0.0, 'kerja'),
 (0.534046329052269, 'lama'),
 (0.0, 'makin'),
 (0.0, 'model'),
 (0.0, 'negara'),
 (0.534046329052269, 'ngurus'),
 (0.0, 'pakai'),
 (0.0, 'rakyat'),
 (0.0, 'sejahtera'),
 (0.0, 'sulam'),
 (0.0, 'tambal')]

In [11]:
vect= TfidfVectorizer(max_features=1000, binary=True)
X = vect.fit_transform(df.text)

X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.22640839, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Membagi data training dan data test untuk menghitung akurasi model

In [13]:
from sklearn.model_selection import train_test_split

x=df.text
y=df.label

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [14]:
#from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(max_features=1000, binary=True,)

X_train_vect = vect.fit_transform(X_train)

In [15]:
#!pip install imblearn
#pip intall SMOTE
#from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

sm = SMOTE()

X_train_res, y_train_res = sm.fit_resample(X_train_vect, y_train)

In [16]:
unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))

[(-1, 89), (1, 89)]


# Naive bayes classification

In [17]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train_res, y_train_res)

nb.score(X_train_res, y_train_res)

0.9606741573033708

In [18]:
X_test_vect = vect.transform(X_test)

y_pred = nb.predict(X_test_vect)

y_pred

array([ 1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,
        1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1,  1, -1, -1,  1], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

print("Accuracy : {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score : {:.2f}%".format(f1_score(y_test, y_pred, average='weighted')*100))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred))

Accuracy : 81.82%

F1 Score : 81.82%

Confusion Matrix : 
 [[15  4]
 [ 4 21]]


# proses training naive bayes classification

In [22]:
import os 
import pickle
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

x = df.text
y = df.label

text_classifier = Pipeline([('vect', TfidfVectorizer()), ('tfidf', TfidfTransformer()), ('classifier', MultinomialNB(alpha=1.0)),])

X_train = np.asarray(x)
Model_classifier_nbc = text_classifier.fit(X_train, np.asarray(y))

In [72]:
tweet_test = ['ayo percaya jokowi naik harga sembako bbm minyak goreng couste1ujwox',
'86 684 warga pandeglang blt minyak goreng ayo percaya jokiwi cokdl6azfvry',
'cahyaniika3 blt minyak goreng cair minggu kantor pos ayo percaya jokowi cofd4k9el6xf',
'makan bahan minyak goreng alternatif menu sehat pas minyak goreng habis dapur bening tempe bumbu kuning botok teri daun singkong selera pedes sila bw nasi eh puasa rabu bening open order botok daun singkong covjgz741oxa',
'pemkab kubu raya unik distribusi minyak goreng curah manfaat data laku umkm data sistem informasi geospasial distribusimigor cowhbegqrcec',
'perintah gelontor rp695 triliun bantu langsung tunai blt minyak goreng ramadan simak skema salur infografis cnnindonesia cooydmvq21gf co3twjwtj3t6',
'ayo percaya jokowi blt minyak goreng cair minggu kantor pos copnqxs7y5h4',
'masreyhaan sorry zaman habibie beras harga 6000 turun sampe 2000 gusdur minyak goreng nasional gua saudara jual migordi tv harga 4000 ehhh pasar modal toko 6000 antem jual beli lupa',
'an asosiasi dagang pasar mang penting presiden joko widodo ecek tinjau harga minyak goreng pasar rakyat menteri bumn erick thohir peran bumn layan masyarakat bai',
'sobat bumn bumn holding pangan distribusi minyak goreng pasar pasar rakyat 17 juta liter distribusi minyak goreng wujud kolaborasi bumn pangan id food group badan pangan nasional menteri dagang menteri industri cozysumgpdh7',
'pasti dian minyak goreng kapolres jaktim kunjung pasar cibubur ciracas cod5ukhz1pre',
'bumn holding pangan distribusi minyak goreng pasar pasar rakyat 17 juta liter distribusi minyak goreng wujud kolaborasi bumn pangan id food group badan pangan nasional menteri dagang kolaborasiatasimigor idfoodofficial co7pdm3i24op',
'mantap berkat kerja keras perintah stok minyak goreng curah limpah bestiee dukungmendaglutfi co4mtknnpplb',
'giat bhabinkamtibmas kel beras basah polsek pangkal susu brigadir j a siregar laksana giat kece sedia minyak goreng kel beras basah kec pangkal susu cou3oi0oognc',
'henryj4ck alingabalinnew alingabalinnew kemendag erickthohir beli minyak goreng subsidi pakai ktp partaisocmed cogqinyojl6c',
'salah alas dukung ridwankamil beliau solutif beliau luncur aplikasi sapawarga mudah masyarakat beli minyak goreng curah subsidi antri solutif 2024ridwankamilpresiden indonesiajuara con91lirufof',
'hujan besti untung salur blt minyak goreng kantor pos antar langsung tugas khawatir dah dukungmendaglutfi cokofsatty03',
'litachanlai2 alhamdulillah berkah puasa minyak goreng al quran',
'riah acara damai indonesia tvone kemarin sinar mas riah bantu minyak goreng wakaf alquran serta vaksin booster salut berkah puasa codiq2gxx2uv',
'realisasi salur blt minyak goreng surabaya capai 72 persen bltminyakgoreng ericahyadi kemensos penyaluranbltminyakgorengdisurabayacapai72persen walikotasurabaya coyky6z4vukh coeqy5ebbhz9',
'mandiraja babinsa koramil 07 mandiraja monitoring salur dana bpnt minyak goreng aula balai desa somawangi 1804 kodim banjarnegara babinsa0704 babinsa bersamarakyattnikuat tniad tni codbd8injplx',
'giat bhabinkamtimas polsek sipispis monitoring sedia minyak goreng kec sipispis cop9xox8gelb',
'ridwan kamil lepas kirim perdana minyak goreng curah pes via aplikasi cornn06mzhji',
'distribusi blt minyak goreng ntb target tuntas lebaran co0pi88aie4h',
'daftar blt minyak goreng rp 300 ribu online cosd9gc2eme3',
'perintah laku cepat distribusi blt minyak goreng jelang lebaran dukungmendaglutfi co1gx3sf38b5',
'lapis masyarakat suka cita blt minyak goreng dukungmendaglutfi coqkymnlumnv',
'renahoston178 rakornas program bantu tunai pangan blt minyak goreng menteri koordinator bidang ekonomi airlangga hrt panglima tentara nasional indonesia jenderal andika perkasa airlanggasolusiekonomirakyat cozdigc6tdne',
'salur beras usaha abdul rasyid salur 100 ribu liter minyak goreng seluruh penjuru kalimantan publisherstory cowr3l3etcza',
'perintah terbit atur sedia minyak goreng usaha mikro co7tsge0s6ii',]

In [73]:
pd.DataFrame(tweet_test)

0
0   ayo percaya jokowi naik harga sembako bbm miny...
1   86 684 warga pandeglang blt minyak goreng ayo ...
2   cahyaniika3 blt minyak goreng cair minggu kant...
3   makan bahan minyak goreng alternatif menu seha...
4   pemkab kubu raya unik distribusi minyak goreng...
5   perintah gelontor rp695 triliun bantu langsung...
6   ayo percaya jokowi blt minyak goreng cair ming...
7   masreyhaan sorry zaman habibie beras harga 600...
8   an asosiasi dagang pasar mang penting presiden...
9   sobat bumn bumn holding pangan distribusi miny...
10  pasti dian minyak goreng kapolres jaktim kunju...
11  bumn holding pangan distribusi minyak goreng p...
12  mantap berkat kerja keras perintah stok minyak...
13  giat bhabinkamtibmas kel beras basah polsek pa...
14  henryj4ck alingabalinnew alingabalinnew kemend...
15  salah alas dukung ridwankamil beliau solutif b...
16  hujan besti untung salur blt minyak goreng kan...
17  litachanlai2 alhamdulillah berkah puasa minyak...
18  riah acara damai indonesia tvone kemarin sinar...
19  realisasi salur blt minyak goreng surabaya cap...
20  mandiraja babinsa koramil 07 mandiraja monitor...
21  giat bhabinkamtimas polsek sipispis monitoring...
22  ridwan kamil lepas kirim perdana minyak goreng...
23  distribusi blt minyak goreng ntb target tuntas...
24  daftar blt minyak goreng rp 300 ribu online co...
25  perintah laku cepat distribusi blt minyak gore...
26  lapis masyarakat suka cita blt minyak goreng d...
27  renahoston178 rakornas program bantu tunai pan...
28  salur beras usaha abdul rasyid salur 100 ribu ...
29  perintah terbit atur sedia minyak goreng usaha...

In [74]:
predicted = Model_classifier_nbc.predict(np.asarray(tweet_test))
predicted

array([ 1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1], dtype=int64)

In [75]:
result_tweet = []

for i in range(len(predicted)):
    if(predicted[i]==1):
        sentiment_result='POSITIF'
    elif(predicted[i]==-1):
        sentiment_result='NEGATIF'
    result_tweet.append({'tweet':tweet_test[i], 'class':predicted[i], 'result_nbc':sentiment_result})

In [76]:
data=pd.DataFrame(result_tweet)
data

tweet  class result_nbc
0   ayo percaya jokowi naik harga sembako bbm miny...      1    POSITIF
1   86 684 warga pandeglang blt minyak goreng ayo ...      1    POSITIF
2   cahyaniika3 blt minyak goreng cair minggu kant...      1    POSITIF
3   makan bahan minyak goreng alternatif menu seha...     -1    NEGATIF
4   pemkab kubu raya unik distribusi minyak goreng...      1    POSITIF
5   perintah gelontor rp695 triliun bantu langsung...      1    POSITIF
6   ayo percaya jokowi blt minyak goreng cair ming...      1    POSITIF
7   masreyhaan sorry zaman habibie beras harga 600...      1    POSITIF
8   an asosiasi dagang pasar mang penting presiden...     -1    NEGATIF
9   sobat bumn bumn holding pangan distribusi miny...      1    POSITIF
10  pasti dian minyak goreng kapolres jaktim kunju...      1    POSITIF
11  bumn holding pangan distribusi minyak goreng p...      1    POSITIF
12  mantap berkat kerja keras perintah stok minyak...      1    POSITIF
13  giat bhabinkamtibmas kel beras basah polsek pa...      1    POSITIF
14  henryj4ck alingabalinnew alingabalinnew kemend...      1    POSITIF
15  salah alas dukung ridwankamil beliau solutif b...      1    POSITIF
16  hujan besti untung salur blt minyak goreng kan...      1    POSITIF
17  litachanlai2 alhamdulillah berkah puasa minyak...      1    POSITIF
18  riah acara damai indonesia tvone kemarin sinar...      1    POSITIF
19  realisasi salur blt minyak goreng surabaya cap...      1    POSITIF
20  mandiraja babinsa koramil 07 mandiraja monitor...      1    POSITIF
21  giat bhabinkamtimas polsek sipispis monitoring...      1    POSITIF
22  ridwan kamil lepas kirim perdana minyak goreng...      1    POSITIF
23  distribusi blt minyak goreng ntb target tuntas...      1    POSITIF
24  daftar blt minyak goreng rp 300 ribu online co...     -1    NEGATIF
25  perintah laku cepat distribusi blt minyak gore...      1    POSITIF
26  lapis masyarakat suka cita blt minyak goreng d...      1    POSITIF
27  renahoston178 rakornas program bantu tunai pan...      1    POSITIF
28  salur beras usaha abdul rasyid salur 100 ribu ...      1    POSITIF
29  perintah terbit atur sedia minyak goreng usaha...      1    POSITIF